### PR TITLE
fix: Update CRUD for metal port to support timeouts

### LINKED ISSUE #357: Timeouts are not honored on Metal resources/data sources
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

`v1.5.4`

### Affected Resource(s)
- Metal Devices resource and datasource
- Metal ports
- Metal VRF
- Network Device
- SSH Key and a few more

### Terraform Configuration Files

```tf
resource "equinix_metal_device" "device" {
  hostname         = "tf-device"
  plan             = var.plan
  metro            = var.metro
  operating_system = var.os
  billing_cycle    = "hourly"
  project_id       = var.project_id
#
  depends_on = [ equinix_metal_project_ssh_key.public_key ]

  timeouts {
    create = "5s"
  }
}
```

### References
Some of the Metal resources/data sources (for example, the equinix_metal_device resource) indicate support for timeouts in their docs and schema, but do not actually support those timeouts.

Per terraform-plugin-sdk v2 docs, we should be using CreateContext, DeleteContext, etc. functions in order to have terraform automatically handle timeouts on our behalf: https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/v2-upgrade-guide#more-support-for-context-context 

Also, for the resources and datasources when the `context aware` timeouts would not be suitable, use Hashicorp's [WaitForStateContext](https://github.com/hashicorp/terraform-plugin-sdk/blob/8bde488a9529d281bc6858ca2b0a3708c2f93658/helper/retry/state.go#L57)

We should find any Metal resources & data sources that have a Timeouts schema property and ensure that those resources & data sources use context-aware CRUD functions.

### Tasks

Upgrade resources and data sources to support context aware or without context CRUD timeouts

- [x] [DataSource and Resource Metal Device support](https://github.com/equinix/terraform-provider-equinix/pull/364)
- [ ] [DataSource and Resource Metal Port support](https://github.com/equinix/terraform-provider-equinix/pull/377)
- [ ] [DataSource and Resource Metal Sport Market Request support](https://github.com/equinix/terraform-provider-equinix/pull/379)
- [x] [DataSource and Resource Metal Virtual Circuit support](https://github.com/equinix/terraform-provider-equinix/pull/380)
- [ ] [DataSource and Resource Metal VRF support](https://github.com/equinix/terraform-provider-equinix/pull/386)
- [x] [Resource Metal Reserved IP Block support](https://github.com/equinix/terraform-provider-equinix/pull/388)
- [x] [Resource Network Device support](https://github.com/equinix/terraform-provider-equinix/pull/387)

### PR DESCRIPTION
**Pull request by aayushrangwala**
- Adds support for timeout in Create, update and delete operation.
- Adds acceptance tests

Fixes #357

### CODE REVIEW

File: equinix/port_helpers.go [hunk 1]
```diff
@@ -126,20 +127,7 @@ func specifiedVlanIds(d *schema.ResourceData) []string {
 	return []string{}
 }
 
-func processVlansOnPort(port *packngo.Port, vlanIds []string, f portVlanAction) (*packngo.Port, error) {
```
Comment (aayushrangwala) [inline equinix/port_helpers.go:129]: Removed because the function is unused

File: equinix/resource_metal_port.go [hunk 2]
```diff
@@ -219,7 +222,7 @@ func resourceMetalPortDelete(d *schema.ResourceData, meta interface{}) error {
 			return err
 		}
 		for _, f := range [](func(*ClientPortResource) error){
```
Comment (displague) [inline equinix/resource_metal_port.go:224]: Should all of the iterated functions (`portSanityChecks`, `makeDisbond`, `convertToL2`, `makeBond`, `convertToL3`, `updateNativeVlan`, (others?)) accept a `context.Context`? 

```suggestion
		for _, f := range [](func(context.Context, *ClientPortResource) error){
```

`batchVlans` would be modified to return `func(context.Context, *ClientPortResource) error` rather than accept context (as in `batchVlans(ctx, start, false)`).

Comment (displague) [reply equinix/resource_metal_port.go:224]: Looking at these helpers, the only ones that would benefit from context are the ones that use the cpr.Client either directly or indirectly. (example https://github.com/equinix/terraform-provider-equinix/blob/a34837fc3b1105075814494ca4edcc52b7f1018d/equinix/port_helpers.go#L213-L216).

Since these are packngo function that don't accept context, your approach seems appropriate. We may want to reconsider this when metal-go is put to use here.

File: equinix/resource_metal_port_acc_test.go [hunk 3]
```diff
@@ -340,3 +378,113 @@ func testAccMetalPortDestroyed(s *terraform.State) error {
...
+		return "", fmt.Errorf("No port with name [%s] found", portName)
+	}
+}
+
+func TestAccMetalPortCreate_hybridBonded_timeout(t *testing.T) {
+	rs := acctest.RandString(10)
+	rInt := acctest.RandInt()
+	deviceName := "equinix_metal_device.test"
+
+	resource.ParallelTest(t, resource.TestCase{
```
Comment (ctreatma) [inline equinix/resource_metal_port_acc_test.go:422]: This test is [failing in CI](https://github.com/equinix/terraform-provider-equinix/actions/runs/6124500596/job/16624681207#step:5:2485), but I'm not sure if it's a persistent failure or tied to something else:
```
=== NAME  TestAccMetalPortCreate_hybridBonded_timeout
    resource_metal_port_acc_test.go:422: Step 3/3 error: Error running destroy: exit status 1
        
        Error: API Error HTTP 422 Cannot delete Virtual Network when port is assigned
```

File: equinix/resource_metal_port.go (hunk 2 above)
Comment (aayushrangwala) [reply equinix/resource_metal_port.go:224]: > Since these are packngo function that don't accept context, your approach seems appropriate. We may want to reconsider this when metal-go is put to use here.
Yes thats right

File: equinix/resource_metal_port_acc_test.go (hunk 3 above)
Comment (ctreatma) [reply equinix/resource_metal_port_acc_test.go:422]: I don't see any 422s in the latest CI run, so I'm going to chalk this up to intermittent issues

**Comment by ctreatma** [comment]
In the latest CI run I see that a bunch of tests are failing due to timeouts right around the 20 minute mark: https://github.com/equinix/terraform-provider-equinix/actions/runs/6251976162/job/16974235659?pr=377#step:5:3981

I'm not clear on whether those timeouts are expected or not, or if we need to increase a default timeout interval somewhere.

**Comment by aayushrangwala** [comment]
> In the latest CI run I see that a bunch of tests are failing due to timeouts right around the 20 minute mark: https://github.com/equinix/terraform-provider-equinix/actions/runs/6251976162/job/16974235659?pr=377#step:5:3981
> 
> I'm not clear on whether those timeouts are expected or not, or if we need to increase a default timeout interval somewhere.

Yes those are failing but they are not expected to fail. In the terraform resource schema we had 20min default timeout but still it seems thats not enough. Trying to update it with 30m probably

Also, I am not sure a port should take more than 20m or 30m ideally to be created. Since we introduced the `usage` of the declared timeouts in this PRs, thats what caused the tests for fail

**Comment by aayushrangwala** [comment]
> Details

Based on this [new](https://github.com/equinix/terraform-provider-equinix/actions/runs/6264685762/job/17042837367?pr=377) test run the metal port timeout specific tests are all passing. Hence it suggests that the overall Acceptances tests may be a bit flaky only sometimes

**Comment by ctreatma** [comment]
> Based on this [new](https://github.com/equinix/terraform-provider-equinix/actions/runs/6264685762/job/17042837367?pr=377) test run the metal port timeout specific tests are all passing. Hence it suggests that the overall Acceptances tests may be a bit flaky only sometimes

I see both `FAIL: TestAccMetalPortUpdate_hybridBonded_timeout` and `FAIL: TestAccMetalPortCreate_hybridBonded_timeout` in the linked test run, as well as in the previous run.

**Comment by aayushrangwala** [comment]
Tests specific to ports are passing now after changing the default timeout to 30 minutes
Screenshot 2023-09-27 at 5 35 44 PM
Screenshot 2023-09-27 at 5 36 38 PM

**Review by ctreatma — APPROVED** [review]
