### PR TITLE
fix delete and import for redundant l2 connections

### LINKED ISSUE #61: Error deleting an Equinix Fabric connection to Equinix Metal service provider - Unexpected state DELETED
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/equinix/equinix v1.1.0
+ provider registry.terraform.io/equinix/metal v3.2.0

### Affected Resource(s)

* equinix_ecx_l2_connection

### Terraform Configuration Files

```tf
resource "equinix_ecx_l2_connection" "this" {
    name              = var.fabric_connection_name
    profile_uuid      = data.equinix_ecx_l2_sellerprofile.this.uuid
    speed             = var.fabric_connection_speed
    speed_unit        = var.fabric_connection_speed_unit
    notifications     = var.fabric_connection_notification_users
    device_uuid       = var.fabric_connection_device_id
    seller_metro_code = var.metal_connection_metro
    authorization_key = metal_connection.this.token

    secondary_connection {
        name        = "${var.fabric_connection_name}-sec"
        device_uuid = var.fabric_secondary_connection_device_id
    }
}
```

### Actual Behavior

The following error is displayed executing terraform destroy:

Error: error waiting for connection (eb566ea0-9618-4205-b9d7-b104d6e90b22) to be removed: unexpected state 'DELETED', wanted target 'PENDING_DELETE, DEPROVISIONED'. last error: %!s(<nil>)

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
### References

* #0000

### LINKED ISSUE #97: named_tag attribute for ecx_l2_connection is not idempotent
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/equinix/equinix v1.2.0
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

ecx_l2_connection 

### Terraform Configuration Files

```tf

data "equinix_ecx_port" "this" {
  name = "this_port"
}

resource "equinix_ecx_l2_connection" "ecx_connection" {

  name                  = "this_pri"
  speed                 = 50
  speed_unit            = "MB"
  notifications         = ["foo@bar.com"]
  purchase_order_number = "this"

  port_uuid         = data.equinix_ecx_port.this.id
  vlan_stag         = 165

  secondary_connection {
    name = "this_sec"
    port_uuid = data.equinix_ecx_port.this.id
    vlan_stag = 166
  }

  seller_metro_code = "DC"
  seller_region     = "eastus"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.this.id
  authorization_key = var.auth_key
  named_tag = "Private"
}
```

### Expected Behavior

Applying the above TF code should succeed in creating the resources, and correctly identify them as unchanged on future runs

### Actual Behavior

The initial creation is a success, but future runs detect a "change" on the named_tag attribute ("PRIVATE" vs "Private").

```
  # module.ecx.equinix_ecx_l2_connection.ecx_connection must be replaced
-/+ resource "equinix_ecx_l2_connection" "ecx_connection" {
      - device_uuid           = "" -> null
      ~ id                    = "c12cc978-...-de255a524478" -> (known after apply)
        name                  = "buildTheFactory-dev_pri"
      ~ named_tag             = "PRIVATE" -> "Private" # forces replacement
      ~ provider_status       = "PENDING_BGP" -> (known after apply)
      ~ redundancy_type       = "PRIMARY" -> (known after apply)
      ~ redundant_uuid        = "" -> (known after apply)
      ~ status                = "PENDING_BGP_PEERING" -> (known after apply)
      ~ uuid                  = "c12cc978-...-de255a524478" -> (known after apply)
      - vlan_ctag             = 0 -> null
      ~ zside_port_uuid       = "66284add-...-30ac094f8af1" -> (known after apply)
      ~ zside_vlan_ctag       = 0 -> (known after apply)
      ~ zside_vlan_stag       = 79 -> (known after apply)
        # (10 unchanged attributes hidden)

      ~ secondary_connection {
          + authorization_key   = (known after apply)
          ~ device_interface_id = 0 -> (known after apply)
            name                = "buildTheFactory-dev_sec"
          + profile_uuid        = (known after apply)
          + provider_status     = (known after apply)
          + redundancy_type     = (known after apply)
          + redundant_uuid      = (known after apply)
          + seller_metro_code   = (known after apply)
          + seller_region       = (known after apply)
          ~ speed               = 0 -> (known after apply)
          + speed_unit          = (known after apply)
          + status              = (known after apply)
          + uuid                = (known after apply)
          - vlan_ctag           = 0 -> null
          + zside_port_uuid     = (known after apply)
          ~ zside_vlan_ctag     = 0 -> (known after apply)
          ~ zside_vlan_stag     = 0 -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Also attempting to use "PRIVATE" as the named_tag as a workaround fails:
```
╷
│ Error: expected named_tag to be one of [Private Public Microsoft Manual], got PRIVATE
│ 
│   with module.ecx.equinix_ecx_l2_connection.ecx_connection,
│   on ../../modules/ecx_vc_red/fp.tf line 31, in resource "equinix_ecx_l2_connection" "ecx_connection":
│   31:   named_tag = "PRIVATE"
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #98: terraform destroy doesn't remove secondary connection
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/equinix/equinix v1.2.0
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.1.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

equinix_ecx_l2_connection

### Terraform Configuration Files

```tf
resource "equinix_ecx_l2_connection" "ecx_connection" {

  name                  = "${local.this_name}_pri"
  speed                 = var.ecx_connection_speed
  speed_unit            = "MB"
  notifications         = var.ecx_notifications
  purchase_order_number = var.ecx_ticket_reference

  port_uuid         = data.equinix_ecx_port.this.id
  vlan_stag         = var.primary_vlan_id

  secondary_connection {
    name = "${local.this_name}_sec"
    port_uuid = data.equinix_ecx_port.this.id
    vlan_stag = var.secondary_vlan_id
  }

  seller_metro_code = var.ecx_region
  seller_region     = var.csp_region
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.this.id
  authorization_key = var.auth_key
  named_tag = var.azure_peering_type
  lifecycle {
    ignore_changes = [ 
      named_tag
    ]
  }
}
```

### Expected Behavior

`Terraform destroy` removes both primary and secondary connection

### Actual Behavior

`Terraform destroy` only removes the primary connection.  this is verified by inspecting the ECX Fabric portal, and the Azure expressroute circuit remaining in the "provisioned" state, so can't be destroyed either.

```
  # module.ecx.equinix_ecx_l2_connection.ecx_connection will be destroyed
  - resource "equinix_ecx_l2_connection" "ecx_connection" {
      - authorization_key     = (sensitive) -> null
      - device_uuid           = "" -> null
      - id                    = "c12cc978-...-de255a524478" -> null
      - name                  = "buildTheFactory-dev_pri" -> null
      - named_tag             = "PRIVATE" -> null
      - notifications         = [
          - "foo@bar.com",
        ] -> null
      - port_uuid             = "91391bf8-...-3eea8c00a876" -> null
      - profile_uuid          = "a1390b22-...-85beef9d254d" -> null
      - provider_status       = "PENDING_BGP" -> null
      - purchase_order_number = "buildTheFactory-dev" -> null
      - redundancy_type       = "PRIMARY" -> null
      - redundant_uuid        = "" -> null
      - seller_metro_code     = "DC" -> null
      - seller_region         = "eastus" -> null
      - speed                 = 50 -> null
      - speed_unit            = "MB" -> null
      - status                = "PENDING_BGP_PEERING" -> null
      - uuid                  = "c12cc978-...-de255a524478" -> null
      - vlan_ctag             = 0 -> null
      - vlan_stag             = 165 -> null
      - zside_port_uuid       = "66284add-...-30ac094f8af1" -> null
      - zside_vlan_ctag       = 0 -> null
      - zside_vlan_stag       = 79 -> null

      - secondary_connection {
          - device_interface_id = 0 -> null
          - name                = "buildTheFactory-dev_sec" -> null
          - port_uuid           = "91391bf8-...-3eea8c00a876" -> null
          - speed               = 0 -> null
          - vlan_ctag           = 0 -> null
          - vlan_stag           = 166 -> null
          - zside_vlan_ctag     = 0 -> null
          - zside_vlan_stag     = 0 -> null
        }
    }

...


module.ecx.equinix_ecx_l2_connection.ecx_connection: Destroying... [id=c12cc978-1b33-483d-baf0-de255a524478]
module.ecx.equinix_ecx_l2_connection.ecx_connection: Still destroying... [id=c12cc978-1b33-483d-baf0-de255a524478, 10s elapsed]
module.ecx.equinix_ecx_l2_connection.ecx_connection: Destruction complete after 14s
module.erc.azurerm_express_route_circuit.this: Destroying... [id=/subscriptions/b3eeba35-987b-49b5-9b5b-475b690e1a0c/resourceGroups/buildTheFactory-dev-real-tapir/providers/Microsoft.Network/expressRouteCircuits/buildTheFactory-dev]
module.erc.azurerm_express_route_circuit.this: Still destroying... [id=/subscriptions/b3eeba35-987b-49b5-9b5b-...pressRouteCircuits/buildTheFactory-dev, 10s elapsed]
╷
│ Error: waiting for the deletion of Express Route Circuit: (Name "buildTheFactory-dev" / Resource Group "buildTheFactory-dev-real-tapir"): Code="ConflictError" Message="The specified dedicated circuit is not in Deprovisioned state. Please initiate the deprovisioning process with your service provider." Details=[]
│ 
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

### PR DESCRIPTION
**Pull request by ocobleseqx**
**Description:** 

Field `RedundantUUID` was used to check if there was a secondary connection. This field is not been returned for new connections anymore. This field can be deleted from the schema but then it will be required a full scan for all connections in the read function to ensure the `terraform import` command works also for redundant connections.

From [terraform import function docs](https://www.terraform.io/plugin/sdkv2/resources/import): 
> This function requires the Read function to be able to refresh the entire resource with d.Id() ONLY

Without `redundantUUID` field returned from the API there is no way to know if it is a redundant connection just with the primary connection ID, since all connections both single and redundant have a `redundancyGroup`. Therefore it will be needed a full scan in the read function to search for a connection with same RedundancyGroup.

To handle that without a full scan I propose to keep `RedundantUUID` but without using the value returned from the API. Instead value will be set in:

- Create function  
https://github.com/equinix/terraform-provider-equinix/blob/e13dbf15a15a165ed08ec74a38907e8dbd4853d2/equinix/resource_ecx_l2_connection.go#L620-L625
- Importer will require users to specify both primary and secondary ID 
https://github.com/equinix/terraform-provider-equinix/blob/e13dbf15a15a165ed08ec74a38907e8dbd4853d2/equinix/resource_ecx_l2_connection.go#L130-L141

**Depends on:**

- [x] new ecx-go version v2.1.1 https://github.com/equinix/ecx-go/pull/5

**Tasks:**

- [x] Fix check for redundancy connections and wait for secondary connection to be deleted - fixes #98 
- [x] Add deleted value as valid target status in delete function  - fixes #61 
- [x] Add named_tag uppercase values field and changes comparison not case-sensitive - fixes #97
- [x] Update l2_connection documentation
- [x] Update e2e test
image

### CODE REVIEW

File: equinix/resource_ecx_l2_connection.go [hunk 1]
```diff
@@ -585,42 +614,21 @@ func resourceECXL2ConnectionCreate(ctx context.Context, d *schema.ResourceData,
 		return diag.FromErr(err)
 	}
 	d.SetId(ecx.StringValue(primaryID))
```
Comment (displague) [inline equinix/resource_ecx_l2_connection.go:616]: > To handle that without a full scan I propose to keep RedundantUUID but without using the value returned from the API. Instead value will be set in _[ID and RedundantUUID, set during creation]_

We could store `primaryID:secondaryID` as the ID. Do you think that would help?

On new connections, we would have in the ID all of the data to refresh the state of the resource.

Although I can't think of any scenarios off the top of my head, it seems like relying on any other state, such as`RedundantUUID`, for refreshes could be risky.

**Review by displague — COMMENTED** [review]
> Without redundantUUID field returned from the API there is no way to know if it is a redundant connection just with the primary connection ID, since all connections both single and redundant have a redundancyGroup.

Should we add a data source for querying a connection based on any combination of the following filters:
- connection id
- redundancy group
- primary/secondary
- others?

**Comment by ocobleseqx** [comment]
> Is this the only way users would be able to get Terraform details for the redundant connection?

Since secondary connection has its own UUID/name it could be retrieved independently:

```
data "equinix_ecx_l2_connection" "primary" {
  name = var.primary_conn_name
  redundancy_group_id = var.redundancy_group_id
}

data "equinix_ecx_l2_connection" "secondary" {
  name = var.secondary_conn_name
  redundancy_group_id = var.redundancy_group_id
}
```

File: equinix/resource_ecx_l2_connection.go (hunk 1 above)
Comment (ocobleseqx) [reply equinix/resource_ecx_l2_connection.go:616]: My concern is that users in terraform are used to the `.id` to reference resources and not the `.uuid` so a change like that would put more complexity/responsibilities on the user side. It would also introduce a breaking change, while using RedundantUUID users will no experiment any change

Comment (displague) [reply equinix/resource_ecx_l2_connection.go:616]: I wasn't considering use of `.id`. That's a good reason not to change things.

File: equinix/resource_ecx_l2_connection.go [hunk 2]
```diff
@@ -115,14 +117,27 @@ var ecxL2ConnectionActionDataDescriptions = map[string]string{
 	"ValidationPattern": "Action data pattern",
 }
 
+type (
```
Comment (displague) [inline equinix/resource_ecx_l2_connection.go:120]: I wonder what `gofumpt` would say about this.

File: equinix/resource_ecx_l2_connection.go [hunk 3]
```diff
@@ -696,38 +716,28 @@ func resourceECXL2ConnectionDelete(ctx context.Context, d *schema.ResourceData,
...
-		Timeout:    d.Timeout(schema.TimeoutDelete),
-		Delay:      2 * time.Second,
-		MinTimeout: 2 * time.Second,
-		Refresh: func() (interface{}, string, error) {
-			resp, err := conf.ecx.GetL2Connection(d.Id())
-			if err != nil {
-				return nil, "", err
+			restErr, ok := err.(rest.Error)
+			if ok {
+				// IC-LAYER2-4021 = Connection already deleted
```
Comment (displague) [inline equinix/resource_ecx_l2_connection.go:726]: nit: this could be `ok && ...`

**Review by displague — APPROVED** [review]
