### PR TITLE
fix: restore the metal_project datasource name filter

### LINKED ISSUE #549: [Bug]: datasource equinix_metal_project doesn't work searching by name
### Terraform Version

Terraform v1.7.1 on darwin_amd64

### Equinix Provider Version

provider registry.terraform.io/equinix/equinix v1.26.0

### Effected Terraform Resources

datasource equinix_metal_project

### Terraform Config Files

_No response_

### Debug Output

_No response_

### Panic Output

_No response_

### Expected Behavior

find the existing project

### Actual Behavior

```
2024-01-31T17:03:19.450+0100 [TRACE] terraform.contextPlugins: Schema for provider "registry.terraform.io/equinix/equinix" is in the global cache
╷
│ Error: no project found with name ocm-tf-test
│ 
│   with data.equinix_metal_project.foobar,
│   on main.tf line 14, in data "equinix_metal_project" "foobar":
│   14: data "equinix_metal_project" "foobar" {
│ 
```
However I can retrieve that project by id

```
# Get Project 
data "equinix_metal_project" "foobar" {
  # name = "ocm-tf-test"
  project_id = "b3b111d4-a313-4132-a824-XXXX"
}
```

```
2024-01-31T17:09:06.422+0100 [TRACE] Completed graph transform *terraform.TransitiveReductionTransformer (no changes)

Changes to Outputs:
  + name = "ocm-tf-test"

```

### Steps to Reproduce

```
terraform {
  required_providers {
    equinix = {
      source = "equinix/equinix"
      # version = "9.0.0"
    }
  }
}

# Credentials for all Equinix resources
provider "equinix" {}

# Get Project by name
data "equinix_metal_project" "foobar" {
  name = "ocm-tf-test"
}
```

`terraform apply`

### PR DESCRIPTION
**Pull request by ctreatma**
Closes #549

When the Metal project data source was migrated to `equinix-sdk-go`, finding a project by name was broken in some cases.  To ensure that the data source can always find the named project (assuming it really exists), we have to use the `ExecuteWithPagination()` function to load all pages of projects instead of `Execute()` which only loads one page.

As a minor optimization, this uses the `Name()` filter to reduce the number of results that are returned by the API.

I've also taken the opportunity to move the Metal project resource and data source to a separate package.

### CODE REVIEW

File: internal/resources/metal/project/datasource.go [hunk 1]
```diff
@@ -121,12 +121,12 @@ func dataSourceMetalProjectRead(ctx context.Context, d *schema.ResourceData, met
 	if nameOK {
 		name := nameRaw.(string)
 
-		os, _, err := client.ProjectsApi.FindProjects(ctx).Execute()
+		projects, err := client.ProjectsApi.FindProjects(ctx).Name(name).ExecuteWithPagination()
```
Comment (ctreatma) [inline internal/resources/metal/project/datasource.go:124]: This is the line change that fixes #549.  Adopting `ExecuteWithPagination` on its own is enough to fix the bug: that function will load all projects available to the current token, as was done in the `packngo` implementation.  I added the `Name` filter as an optimization but can remove it if reviewers aren't comfortable with taking that risk.

**Review by displague — APPROVED** [review]
