### PR TITLE
Keep value of metal_connection.vlans in sync with API

### LINKED ISSUE #270: metal_connection resource and data source do not read VLAN IDs from API
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Affected Resource(s)

* equinix_metal_connection

### Terraform Configuration Files

```tf

resource "equinix_metal_connection" "example" {
    name               = "tf-testing-vlans"
    project_id         = local.project_id
    type               = "shared"
    redundancy         = "redundant"
    metro              = "SV"
    speed              = "1Gbps"
    service_token_type = "a_side"
    vlans = [
        equinix_metal_vlan.vlan2.vxlan,
        equinix_metal_vlan.vlan3.vxlan
    ]
}

data "equinix_metal_connection" "example" {
    connection_id = equinix_metal_connection.example.id
}

output "datasource_vlans" {
    value = data.equinix_metal_connection.example.vlans
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The `datasource_vlans` attribute should be a list of 2 VLAN IDs.

### Actual Behavior

The `datasource_vlans` output is empty

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by ctreatma**
This updates the `metal_connection` resource and data source to read the value of `vlans` from the API response to ensure that terraform state stays up-to-date with the real infrastructure if someone modifies the VLANs for a terraform-managed `metal_connection` outside of terraform.

Closes #270

### CODE REVIEW

File: equinix/data_source_metal_connection_acc_test.go [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+			project_id  = equinix_metal_project.test.id
+		}
+
+        resource "equinix_metal_connection" "test" {
+            name               = "tfacc-conn-%s"
+            project_id         = equinix_metal_project.test.id
+            type               = "shared"
+            redundancy         = "redundant"
+            metro              = "sv"
+			speed              = "50Mbps"
```
Comment (ocobleseqx) [inline equinix/data_source_metal_connection_acc_test.go:105]: It seems there are some extra tabs here

File: equinix/resource_metal_connection.go [hunk 2]
```diff
@@ -383,6 +383,11 @@ func resourceMetalConnectionRead(d *schema.ResourceData, meta interface{}) error
 		return err
 	}
 
+	vlans := getConnectionVlans(conn)
```
Comment (ocobleseqx) [inline equinix/resource_metal_connection.go:386]: nit: you can set `"vlans":              getConnectionVlans(conn),` directly in set map without check in for nil

Comment (ctreatma) [reply equinix/resource_metal_connection.go:386]: I started with adding the attribute in `setMap`, but including the method call directly in `setMap` sets the `vlans` value to `[]` instead of leaving the attribute unset.  In that case, a `metal_connection` that has no `vlans` specified will always show changes in `terraform plan` b/c terraform wants to unset `[]`.

It's possible we could get around that by specifying a default value of `[]` for `vlans`?  I'm not sure if changing/adding that default would cause problems elsewhere, so I went with the `nil` check to minimize impact on existing code.

**Review by ocobleseqx — APPROVED** [review]
